- hosts: localhost
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/dotfiles.yml
    - include: tasks/node-setup.yml
    - include: tasks/python-setup.yml
    - include: tasks/fonts-setup.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/tmux-setup.yml
    - include: tasks/obsidian-setup.yml
    - include: tasks/go-setup.yml
